### ISSUE TITLE
Project Repository Information

### ISSUE THREAD

**Issue by david-kariuki** [kachuma/project101#1]
Hello, how are you? I noticed you invited me to collaborate on this project repo. What is this project about? Do you mind sharing more information about this?

**Comment by kachuma** [comment]
Hi David

It is just a school project, I'm doing software engineering and just
familiarise myself with Github

Hope no offense


Kind regards

**Comment by david-kariuki** [comment]
That's alright, no offense. I hope to work with you on something interesting soon.

**Comment by kachuma** [comment]
No problem!

I would like that
